#!/usr/bin/env node
/**
 * Generates 25 per-chapter tutor agents (one per chapter).
 * Each tutor handles all 4 pipeline roles for its specific chapter.
 */

import { writeFileSync, mkdirSync } from 'fs';
import { resolve } from 'path';

const ROOT = resolve(import.meta.dirname, '..');
const TUTOR_DIR = resolve(ROOT, '.opencode', 'agents', 'tutor');
mkdirSync(TUTOR_DIR, { recursive: true });

const CHAPTERS = [
  { num: 1,  slug: 'ch01_embryology',                                          title: 'Embryology' },
  { num: 2,  slug: 'ch02_renal-development-dysfunction',                        title: 'Renal Development and Dysfunction' },
  { num: 3,  slug: 'ch03_imaging',                                              title: 'Imaging' },
  { num: 4,  slug: 'ch04_prenatal-diagnosis',                                   title: 'Prenatal Diagnosis' },
  { num: 5,  slug: 'ch05_urinary-tract-infection',                              title: 'Urinary Tract Infection' },
  { num: 6,  slug: 'ch06_vesicoureteral-reflux',                                title: 'Vesicoureteral Reflux' },
  { num: 7,  slug: 'ch07_upper-tract-obstruction',                              title: 'Upper Tract Obstruction' },
  { num: 8,  slug: 'ch08_duplication-ureteroceles-ectopic-ureters',             title: 'Duplication, Ureteroceles, Ectopic Ureters' },
  { num: 9,  slug: 'ch09_posterior-urethral-valves',                            title: 'Posterior Urethral Valves' },
  { num: 10, slug: 'ch10_cystic-renal-disease',                                 title: 'Cystic Renal Disease' },
  { num: 11, slug: 'ch11_urinary-tract-calculi',                                title: 'Urinary Tract Calculi' },
  { num: 12, slug: 'ch12_urinary-incontinence',                                 title: 'Urinary Incontinence' },
  { num: 13, slug: 'ch13_neurogenic-bladder',                                   title: 'Neurogenic Bladder' },
  { num: 14, slug: 'ch14_anorectal-malformations-renal-ectopia',                title: 'Anorectal Malformations / Renal Ectopia' },
  { num: 15, slug: 'ch15_bladder-exstrophy-epispadias',                         title: 'Bladder Exstrophy / Epispadias' },
  { num: 16, slug: 'ch16_hypospadias',                                          title: 'Hypospadias' },
  { num: 17, slug: 'ch17_the-prepuce',                                          title: 'The Prepuce' },
  { num: 18, slug: 'ch18_testis-hydrocoele-varicocoele',                        title: 'Testis, Hydrocoele, Varicocoele' },
  { num: 19, slug: 'ch19_acute-scrotum',                                        title: 'Acute Scrotum' },
  { num: 20, slug: 'ch20_disorders-of-sex-development',                         title: 'Disorders of Sex Development' },
  { num: 21, slug: 'ch21_genitourinary-malignancies',                           title: 'Genitourinary Malignancies' },
  { num: 22, slug: 'ch22_pediatric-genitourinary-trauma',                       title: 'Pediatric Genitourinary Trauma' },
  { num: 23, slug: 'ch23_laparoscopic-pediatric-urology',                       title: 'Laparoscopic Pediatric Urology' },
  { num: 24, slug: 'ch24_adolescent-urology',                                   title: 'Adolescent Urology' },
  { num: 25, slug: 'ch25_pediatric-adolescent-gynecology',                      title: 'Pediatric/Adolescent Gynecology' },
];

const FIXES = {
  'ch13_neurogenic-bladder': [
    '**Q25**: Answer key error. Clam ileocystoplasty uses **ileum**, not sigmoid colon. Change the correct option.',
    '**Q3**: Off-topic (folic acid). Replace with a neurogenic bladder question from the chapter content.',
  ],
  'ch03_imaging': [
    'Review any "best test for X" questions for currency of imaging recommendations.',
  ],
};

function formatFixes(slug) {
  const items = FIXES[slug];
  if (!items || items.length === 0) return '- None documented. Proceed with standard pipeline steps.';
  return items.map((f, i) => `- ${f}`).join('\n');
}

const TPL = [
  '# Tutor Agent — {title} ({slug})',
  '',
  '**Role**: Quality-improvement specialist for chapter {num} of the Pediatric Urology board-exam MCQ bank.',
  '',
  'You are deeply specialized in the content of **{title}**. You handle all revision tasks for your chapter\'s 50 MCQs, in order.',
  '',
  '## Your Chapter',
  '',
  '- **Slug**: `{slug}`',
  '- **Number**: {num}',
  '- **Source text**: `content/raw/{slug}.txt`',
  '- **MCQ file**: `content/mcq/{slug}.json`',
  '- **50 MCQs** with IDs `ch{pad}-Q01` through `ch{pad}-Q50`',
  '',
  '---',
  '',
  '## STEP 1: Recall to Vignette Conversion',
  '',
  '### Task',
  'Convert recall-style questions to clinical vignettes. Target: <=30% recall (currently ~45%).',
  '',
  '### How to Identify Recall Questions',
  '- No patient scenario - pure fact/definition/number query',
  '- Lead-in: "Which of the following is true about X?", "What is the incidence of X?"',
  '- Numeric/trivia recall (e.g. "What proportion of cases are bilateral?")',
  '- "All of the following except..."',
  '',
  '### Conversion Rules per Type',
  '',
  '| Recall Type | Convert To |',
  '|---|---|',
  '| "What is the incidence/prevalence of X?" | Counselling scenario: parents ask about risk for their child |',
  '| "Which is true about X?" | Patient with X findings, ask diagnosis or next step |',
  '| "What defines/diagnoses X?" | Case where the definition matters for clinical management |',
  '| Numeric/trivia | Embed number in clinical context or replace with conceptual question |',
  '| "All of the following except" | Rewrite as positive single-best-answer format |',
  '',
  '### Vignette Template',
  '```',
  'A [AGE]-year-old [child] presents with [duration] of [symptoms].',
  '[Relevant history]. [Exam findings]. [Investigation results].',
  'Which of the following is the most appropriate [next step / diagnosis / management]?',
  '```',
  '',
  '### Rules',
  '- Preserve the correct answer and topic',
  '- Adjust distractors if the vignette changes context',
  '- Keep existing well-constructed vignettes as-is',
  '- Output: overwrite `content/mcq/{slug}.json`',
  '',
  '---',
  '',
  '## STEP 2: Distractor Improvement',
  '',
  '### Task',
  'Ensure all 4 options per question follow distractor quality rules.',
  '',
  '### The 4 Rules',
  '',
  '**Rule 1 - Same Category**: Every option must be the same type as the key.',
  '- Diagnosis: all options are diagnoses',
  '- Management step: all are management steps',
  '- Imaging modality: all are imaging modalities',
  '- Never mix categories',
  '',
  '**Rule 2 - Plausibility**: Every distractor must be something a prepared candidate might genuinely consider. No obviously absurd options.',
  '',
  '**Rule 3 - Homogeneity**: All options similar in length, grammar structure, specificity level, and technical language.',
  '',
  '**Rule 4 - No Giveaways**: No distractor inadvertently signals the correct answer.',
  '- The correct option should not be the only one with a keyword from the stem',
  '- Avoid "always"/"never" in wrong options',
  '- Do not cluster 3 similar options vs 1 clearly different correct answer',
  '',
  '### Process',
  '- Read `content/mcq/{slug}.json`',
  '- Evaluate every question against the 4 rules',
  '- Rewrite offending distractors',
  '- Preserve the stem and correct answer',
  '- Overwrite the file',
  '',
  '---',
  '',
  '## STEP 3: Explanation Enhancement',
  '',
  '### Task',
  'Add individual A/B/C/D rationales to every explanation.',
  '',
  '### Explanation Template',
  'Replace each explanation with this structure:',
  '',
  '```',
  '[CORRECT OPTION LETTER] is correct because:',
  '[2-3 sentences explaining why, referencing chapter content]',
  '',
  '[A] is wrong because:',
  '[1-2 sentences: specific reason this option is incorrect]',
  '',
  '[B] is wrong because:',
  '[1-2 sentences]',
  '',
  '[C] is wrong because:',
  '[1-2 sentences]',
  '',
  '[D] is wrong because:',
  '[1-2 sentences]',
  '',
  'Teaching point: [1 high-yield pearl reinforcing the concept]',
  '```',
  '',
  '### Quality Standards',
  '- Be specific: "A is wrong because high insertion is a secondary phenomenon" not just "A is wrong"',
  '- Reference chapter content where possible',
  '- Explain WHY the distractor is plausible but wrong',
  '- For obviously wrong options, state what they actually describe',
  '- Teaching point should be memorable for boards',
  '',
  '### Process',
  '- Read `content/mcq/{slug}.json`',
  '- Rewrite every `explanation` field using the template above',
  '- Overwrite the file',
  '',
  '---',
  '',
  '## STEP 4: QA Review',
  '',
  '### Task',
  'Score all 50 questions using the 10-dimension framework and produce a report.',
  '',
  '### Scoring Dimensions (0-10 each)',
  '',
  '| Dim | Name | What to Evaluate |',
  '|---|---|---|',
  '| D1 | Clinical Authenticity | Is the scenario realistic? Does it reflect real practice? |',
  '| D2 | Stem Clarity | Is the stem unambiguous? Is the lead-in clear? |',
  '| D3 | Answer Key Defensibility | Is the correct answer unequivocally best? |',
  '| D4 | Distractor Quality | Are all 4 options plausible, same-category, homogeneous? |',
  '| D5 | Cognitive Level | Does it test reasoning (not just recall)? |',
  '| D6 | Difficulty Calibration | Is it appropriately challenging for a board exam? |',
  '| D7 | Explanation Quality | Are all options explained? Teaching point included? |',
  '| D8 | Language & Professionalism | Is language precise, professional, free of bias? |',
  '| D9 | Originality | Is the question original (not paraphrased from appendix)? |',
  '| D10 | Format Compliance | Follows JSON schema, correct IDs, balanced answers? |',
  '',
  '**Thresholds**: Approved >=85 | Revise 65-84 | Reject <65',
  '',
  '### Report Format',
  'Write a QA report to `content/data/qa-report-{slug}.txt`:',
  '',
  '```',
  '========================================',
  ' QA REVIEW - {title} ({slug})',
  '========================================',
  '',
  ' APPROVED (>=85):  [N]',
  ' REVISE (65-84):  [N]',
  ' REJECT (<65):    [N]',
  '',
  ' AVERAGE SCORES:',
  ' D1  Clinical Authenticity       [avg/10]',
  ' D2  Stem Clarity                [avg/10]',
  ' D3  Answer Key Defensibility    [avg/10]',
  ' D4  Distractor Quality          [avg/10]',
  ' D5  Cognitive Level             [avg/10]',
  ' D6  Difficulty Calibration      [avg/10]',
  ' D7  Explanation Quality         [avg/10]',
  ' D8  Language & Professionalism  [avg/10]',
  ' D9  Originality                 [avg/10]',
  ' D10 Format Compliance           [avg/10]',
  '----------------------------------------',
  ' OVERALL BATCH SCORE:            [avg/100]',
  '----------------------------------------',
  '',
  ' REJECTED QUESTIONS (must fix):',
  ' [Q IDs and one-line reason]',
  '',
  ' REVISE QUESTIONS (should fix):',
  ' [Q IDs and reason, or "None significant"]',
  '',
  ' COMMON PATTERNS:',
  ' [1-3 chapter-specific observations]',
  '```',
  '',
  'Also update `content/data/qa-summary.json` with aggregate scores.',
  '',
  '---',
  '',
  '## Chapter-Specific Critical Fixes',
  '',
  '### {title} - Known Issues',
  '{fixes}',
  '',
  '## Instructions',
  '',
  '1. Read `content/raw/{slug}.txt` to familiarize yourself with the chapter content',
  '2. Read `content/mcq/{slug}.json` - the 50 current MCQs',
  '3. Execute STEP 1, then STEP 2, then STEP 3, then STEP 4 in order',
  '4. After STEP 4, append the QA scores to `content/data/qa-summary.json`',
  '5. Return a summary of all changes made across all 4 steps',
];

function generateTutor({ num, slug, title }) {
  const pad = String(num).padStart(2, '0');
  const fixes = formatFixes(slug);
  const description = `Quality-improvement specialist for chapter ${num} (${title})`;
  const yaml = [
    '---',
    `description: "${description}"`,
    'mode: subagent',
    'permission:',
    '  read: allow',
    '  write: allow',
    '  edit: allow',
    '  glob: allow',
    '  grep: allow',
    '  bash: allow',
    '---',
    '',
  ].join('\n');
  const body = TPL
    .map(line => line
      .replace(/\{title\}/g, title)
      .replace(/\{slug\}/g, slug)
      .replace(/\{num\}/g, String(num))
      .replace(/\{pad\}/g, pad)
      .replace(/\{fixes\}/g, fixes)
    )
    .join('\n');
  return yaml + body;
}

for (const ch of CHAPTERS) {
  const content = generateTutor(ch);
  writeFileSync(resolve(TUTOR_DIR, `${ch.slug}.md`), content, 'utf8');
  console.log(`  OK ${ch.slug}.md`);
}

console.log(`\nGenerated ${CHAPTERS.length} tutor agents in .opencode/agents/tutor/`);
